// Data dummy employee
export const employees = [
  {
    id: "1",
    name: "Ahmad Rizki Pratama",
    department: "IT",
    position: "Software Engineer",
    employee_status: "Permanent",
  },
  {
    id: "2",
    name: "Siti Nurhaliza",
    department: "HR",
    position: "HR Manager",
    employee_status: "Permanent",
  },
  {
    id: "3",
    name: "Budi Santoso",
    department: "Finance",
    position: "Financial Analyst",
    employee_status: "Permanent",
  },
  {
    id: "4",
    name: "Maya Sari Dewi",
    department: "Marketing",
    position: "Marketing Specialist",
    employee_status: "Permanent",
  },
  {
    id: "5",
    name: "Andi Wijaya",
    department: "Operations",
    position: "Operations Manager",
    employee_status: "Permanent",
  },
  {
    id: "6",
    name: "Rina Kartika",
    department: "Sales",
    position: "Sales Executive",
    employee_status: "Permanent",
  },
  {
    id: "7",
    name: "Dedi Kurniawan",
    department: "IT",
    position: "System Administrator",
    employee_status: "Permanent",
  },
  {
    id: "8",
    name: "Lestari Wulandari",
    department: "HR",
    position: "HR Specialist",
    employee_status: "Permanent",
  },
  {
    id: "9",
    name: "Fajar Nugroho",
    department: "Finance",
    position: "Accountant",
    employee_status: "Permanent",
  },
  {
    id: "10",
    name: "Indira Safitri",
    department: "Marketing",
    position: "Content Creator",
    employee_status: "Permanent",
  },
  {
    id: "11",
    name: "Reza Firmansyah",
    department: "IT",
    position: "Frontend Developer",
    employee_status: "Permanent",
  },
  {
    id: "12",
    name: "Dewi Anggraini",
    department: "Operations",
    position: "Quality Assurance",
    employee_status: "Permanent",
  },
  {
    id: "13",
    name: "Hendra Setiawan",
    department: "Sales",
    position: "Sales Manager",
    employee_status: "Permanent",
  },
  {
    id: "14",
    name: "Putri Maharani",
    department: "Marketing",
    position: "Digital Marketing",
    employee_status: "Permanent",
  },
  {
    id: "15",
    name: "Agus Prasetyo",
    department: "Finance",
    position: "Finance Manager",
    employee_status: "Permanent",
  },
  {
    id: "16",
    name: "Nita Puspita",
    department: "HR",
    position: "Recruitment Specialist",
    employee_status: "Permanent",
  },
  {
    id: "17",
    name: "Bayu Aditama",
    department: "IT",
    position: "Backend Developer",
    employee_status: "Permanent",
  },
  {
    id: "18",
    name: "Citra Melati",
    department: "Operations",
    position: "Project Coordinator",
    employee_status: "Permanent",
  },
  {
    id: "19",
    name: "Dimas Pratama",
    department: "Sales",
    position: "Business Development",
    employee_status: "Permanent",
  },
  {
    id: "20",
    name: "Eka Rahayu",
    department: "Marketing",
    position: "Brand Manager",
    employee_status: "Permanent",
  },
];
